### ISSUE TITLE
make combined branch for AP delivery with all algos

### ISSUE THREAD

**Issue by falko-strenzke** [pqc-thunderbird/libgcrypt#49]
* ML-KEM (with AVX2)
* ML-DSA (with AVX2)
* SLH-DSA (with AVX2)
* KMAC

**Comment by TJ-91** [comment]
~~For the delivery I just noticed that I still need to do #50~~
done

**Comment by falko-strenzke** [comment]
use all the AVX2 branches and KMAC branch

- [ ] JRH macht einen kombinierten branch aus den AVX2

**Comment by falko-strenzke** [comment]
The branch `all-pqc` already has `kyber-avx2`  and `kmac`  branches merged.

**Comment by TJ-91** [comment]
all algorithms are merged now (merged `dilithium_avx2` and `sphincsplus_avx2`).
