### ISSUE TITLE
missing fixes from standard branch for ML-DSA

### ISSUE THREAD

**Issue by falko-strenzke** [pqc-thunderbird/libgcrypt#55]
* [x] Bug is described in https://github.com/pq-crystals/dilithium/commit/32271b821f7244b8b91ec42e1f5ee657956732b1  #f597d5bf
* [x] Another described here https://github.com/pq-crystals/dilithium/commit/e7bed6258b9a3703ce78d4ec38021c86382ce31c  #19a24a58

**Comment by TJ-91** [comment]
We should implement the first (even if it has no effect currently). The second is irrelevant to us because the respective code is removed in our implementation

**Comment by falko-strenzke** [comment]
At least to document in AP 5 doc that there is no need to change the implementation.

**Comment by TJ-91** [comment]
updated the code, it is now at commit 32271b8 (of the ref. impl)

**Comment by falko-strenzke** [comment]
is the 2nd bug in the issue body still open?

**Comment by TJ-91** [comment]
It's not relevant to our code so I checked the box now

**Comment by falko-strenzke** [comment]
Then I think we can close this issue ? (Closing it it hereby)
