### ISSUE TITLE
verify that changes to ML-DSA after 3rd round are included

### ISSUE THREAD

**Issue by falko-strenzke** [pqc-thunderbird/libgcrypt#57]
For a summary of the changes after round 3, see https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.204.ipd.pdf#page=13

**Comment by TJ-91** [comment]
Looks to me like all changes from the reference implementation standard branch are incorporated in our code and that all changes that are indicated in the ML-DSA draft are in the standard-branch.
