### ISSUE TITLE
ML-DSA: Check hint bit checking in our implementation

### ISSUE THREAD

**Issue by falko-strenzke** [pqc-thunderbird/libgcrypt#59]
see https://groups.google.com/a/list.nist.gov/d/msgid/pqc-forum/GVXPR07MB9678F1C6A1B7441AD9A81AAB89452%40GVXPR07MB9678.eurprd07.prod.outlook.com?utm_medium=email&utm_source=footer

§§rem-eff:2h

**Comment by TJ-91** [comment]
This is merely a bug in the pseudo code / description in the NIST/Round3 spec, not in the reference code, therefore not relevant to our project.

> The Dilithium reference code at https://github.com/pq-crystals/dilithium/blob/master/ref/packing.c appears to check that the hints are in ascending order.  I don’t see where the round 3 specification specifies how to encode the hints at all, beyond Section 3’s vague:
